### ISSUE TITLE
Emulator runs less fast than the real Agon Light under Windows

### ISSUE THREAD

**Issue by DjPoke** [tomm/fab-agon-emulator#13]
Hi,
Can you accelerate a little the emulator ? My Agon Light 2 runs a little faster.

**Comment by astralaster** [comment]
Can you supply a test which shows this behavior? What exactly is faster?

**Comment by DjPoke** [comment]
I think playing sounds reduce speed on the emulator. Sounds plays more slowly, and impact speed.

**Comment by DjPoke** [comment]
This is a game i'm working on : [](https://cpclike.com/downloads/NorthPinball.zip)
Once the screen is loaded, and after the first sound, push Enter key, and look at the ball bouncing. Push shift L and R keys.
Listen also the sounds. And after, compare the emulator version with the real Agon Light version.

**Comment by DjPoke** [comment]
The 1.0.4 RC2 firmware is faster thant the 1.0.4 RC1. That solve the problem.
