### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Chandler-Kluser** [tomm/fab-agon-emulator#39]
# Issue

Running `./fab-agon-emulator` launches a GTK4 window with a blackscreen:

![image](https://github.com/tomm/fab-agon-emulator/assets/29960960/6bc12ebf-c327-410b-b798-ac5283f7402d)

## Steps

- Clone Repository
- Change Directory to Repository
- Import Submodules
- Run GNU Make
- Run `./fab-agon-emulator`

## Tips

- Workarounds like running with MOS and VDP variants don't solve the issue
- No cargo complaints when building source code (only a gamepad warning)
- Soft resetting the emulator get a beep sound, so I think it is actually a video only SDL issue

## System Info

```text
                   -`                    chandler@pc-quarto 
                  .o+`                   ------------------ 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: B450 I AORUS PRO WIFI 
               `+oooooo:                 Kernel: 6.6.10-arch1-1 
               -+oooooo+:                Uptime: 5 days, 13 hours, 39 mins 
             `/:-:++oooo+:               Packages: 1858 (pacman) 
            `/++++/+++++++:              Shell: zsh 5.9 
           `/++++++++++++++:             Resolution: 3840x2160 
          `/+++ooooooooooooo/`           DE: GNOME 45.3 
         ./ooosssso++osssssso+`          WM: Mutter 
        .oossssso-````/ossssss+`         WM Theme: Adwaita 
       -osssssso.      :ssssssso.        Theme: HighContrastInverse [GTK2/3] 
      :osssssss/        osssso+++.       Icons: Adwaita [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: kgx 
   `/ossssso+/:-        -:/+osssso+-     CPU: AMD Ryzen 7 3700X (16) @ 3.600GHz 
  `+sso+:-`                 `.-/+oso:    GPU: AMD ATI Radeon RX 6600/6600 XT/6600M 
 `++:.                           `-/+/   Memory: 10456MiB / 15912MiB 
 .`                                 `/
```

**Comment by astralaster** [comment]
Please post the console output, too.

**Comment by Chandler-Kluser** [comment]
![image](https://github.com/tomm/fab-agon-emulator/assets/29960960/c68ca5fa-7d18-4bfe-90d0-fb0f2761bd2c)

**Comment by Chandler-Kluser** [comment]
# Debug Info

Building using branch `0.9-dev` does not solve the issue. But, when using the built release from last week the video came out (as expected).

So, my suggestion is:

- Import a static SDL library to not rely on user system libs
- Modify SDL calls to be more compatible with recent libs
- Specify which libs are needed to avoid this black screen issue (and append in README.md in a "Known Issues" category)

## Interesting Fact

Curiously, copying `sdcard` and `firmware` contents from binary release to the built from source `0.9-dev` branch gets this segmentation fault error:

```bash
$ ./fab-agon-emulator
[1]    2220818 segmentation fault (core dumped)  ./fab-agon-emulator
```

**Comment by Chandler-Kluser** [comment]
Somehow the issue has been solved in a recent commit, closing
