### ISSUE TITLE
sdl::init and video subsystem on main thread

### ISSUE THREAD

**Issue by S0urceror** [tomm/fab-agon-emulator#49]
After getting your last changes I noticed that on my Mac the emulator was crashing at startup:
<img width="792" alt="image" src="https://github.com/tomm/fab-agon-emulator/assets/4992808/25fdc384-7473-4dc1-89eb-efef4b5ea201">

I noticed this was due to SDL::initialisation is now happening on a separate UI thread. According to the SDL folks this is not recommended.

When reverting back to running on the main thread everything works again:
<img width="645" alt="image" src="https://github.com/tomm/fab-agon-emulator/assets/4992808/9662a303-facc-4b80-8513-faef0eabee3b">

<img width="642" alt="image" src="https://github.com/tomm/fab-agon-emulator/assets/4992808/fe1dda10-011a-4344-95f4-bd1475739135">

**Comment by tomm** [comment]
Oops. Reverted that mistake. Thanks
