### ISSUE TITLE
Doesn't Build / Run under macOS

### ISSUE THREAD

**Issue by snakebyte69** [tomm/fab-agon-emulator#6]
make                  : Does not work
cargo build -r    : Works
cargo run -r       : Does not work

**Comment by tomm** [comment]
I have no apple hardware so will need some help with getting build working on MacOS. Sorry!

**Comment by snakebyte69** [comment]
% make

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C userspace-vdp
c++ -Wall -O2 -fmax-errors=1 -g -I. -I./dispdrivers  -fPIC -c canvas.cpp
clang: warning: argument unused during compilation: '-fmax-errors=1' [-Wunused-command-line-argument]
In file included from canvas.cpp:29:
In file included from ./canvas.h:41:
In file included from ./displaycontroller.h:48:
./fabutils.h:113:1: error: unknown type name 'constexpr'
constexpr auto imax = tmax<int>;
^
./fabutils.h:113:16: error: illegal storage class on file-scoped variable
constexpr auto imax = tmax<int>;
               ^
./fabutils.h:123:1: error: unknown type name 'constexpr'
constexpr auto imin = tmin<int>;
^
./fabutils.h:123:16: error: illegal storage class on file-scoped variable
constexpr auto imin = tmin<int>;
               ^
./fabutils.h:134:1: error: unknown type name 'constexpr'
constexpr auto iclamp = tclamp<int>;
^
./fabutils.h:134:16: error: illegal storage class on file-scoped variable
constexpr auto iclamp = tclamp<int>;
               ^
./fabutils.h:153:1: error: unknown type name 'constexpr'
constexpr auto iswap = tswap<int>;
^
./fabutils.h:153:16: error: illegal storage class on file-scoped variable
constexpr auto iswap = tswap<int>;
               ^
./fabutils.h:381:10: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    for (auto i = m_items; i; i = i->next)
         ^
./fabutils.h:394:20: warning: variadic templates are a C++11 extension [-Wc++11-extensions]
template <typename ...Params>
                   ^
./fabutils.h:402:34: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
  Delegate(const Delegate & c) = delete;
                                 ^
./fabutils.h:424:37: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
  void operator=(const Delegate&) = delete;
                                    ^
./fabutils.h:418:18: error: expected expression
    m_closure  = [] (void * func, const Params & ...params) -> void { (*(Func *)func)(params...); };
                 ^
./fabutils.h:537:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class DriveType {
     ^
./fabutils.h:953:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class ChipPackage {
     ^
./fabutils.h:1012:1: error: unknown type name 'constexpr'
constexpr int FRC1TimerMax = 8388607;
^
./fabutils.h:1067:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class VideoMode {
     ^
In file included from canvas.cpp:29:
In file included from ./canvas.h:41:
./displaycontroller.h:431:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class NativePixelFormat : uint8_t {
     ^
./displaycontroller.h:445:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class PixelFormat : uint8_t {
     ^
./displaycontroller.h:457:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class LineEnds : uint8_t {
     ^
./displaycontroller.h:474:42: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
  Bitmap() : width(0), height(0), format(PixelFormat::Undefined), foregroundColor(RGB888(255, 255, 255)), data(nullptr), dataAllocated(false) { }
                                         ^
./displaycontroller.h:613:28: error: union member 'color' has a non-trivial default constructor
    RGB888                 color;
                           ^
./displaycontroller.h:234:3: note: because type 'fabgl::RGB888' has a user-provided default constructor
  RGB888() : R(0), G(0), B(0) { }
  ^
./displaycontroller.h:614:28: error: union member 'position' has a non-trivial default constructor
    Point                  position;
                           ^
./fabutils.h:212:3: note: because type 'fabgl::Point' has a user-provided default constructor
  Point() : X(0), Y(0) { }
  ^
In file included from canvas.cpp:29:
In file included from ./canvas.h:41:
./displaycontroller.h:615:28: error: union member 'size' has a non-trivial default constructor
    Size                   size;
                           ^
./fabutils.h:230:3: note: because type 'fabgl::Size' has a user-provided default constructor
  Size() : width(0), height(0) { }
  ^
In file included from canvas.cpp:29:
In file included from ./canvas.h:41:
./displaycontroller.h:616:28: error: union member 'glyph' has a non-trivial default constructor
    Glyph                  glyph;
                           ^
./displaycontroller.h:335:3: note: because type 'fabgl::Glyph' has a user-provided default constructor
  Glyph() : X(0), Y(0), width(0), height(0), data(nullptr) { }
  ^
./displaycontroller.h:617:28: error: union member 'rect' has a non-trivial copy constructor
    Rect                   rect;
                           ^
./fabutils.h:251:3: note: because type 'fabgl::Rect' has a user-provided copy constructor
  Rect(Rect const & r) { X1 = r.X1; Y1 = r.Y1; X2 = r.X2; Y2 = r.Y2; }
  ^
In file included from canvas.cpp:29:
In file included from ./canvas.h:41:
./displaycontroller.h:619:28: error: union member 'paintOptions' has a non-trivial default constructor
    PaintOptions           paintOptions;
                           ^
./displaycontroller.h:599:3: note: because type 'fabgl::PaintOptions' has a user-provided default constructor
  PaintOptions() : swapFGBG(false), NOT(false) { }
  ^
./displaycontroller.h:620:28: error: union member 'glyphsBufferRenderInfo' has a non-trivial default constructor
    GlyphsBufferRenderInfo glyphsBufferRenderInfo;
                           ^
./displaycontroller.h:419:8: note: because type 'fabgl::GlyphsBufferRenderInfo' has no default constructor
struct GlyphsBufferRenderInfo {
       ^
./displaycontroller.h:424:3: note: implicit default constructor suppressed by user-declared constructor
  GlyphsBufferRenderInfo(int itemX_, int itemY_, GlyphsBuffer const * glyphsBuffer_) : itemX(itemX_), itemY(itemY_), glyphsBuffer(glyphsBuffer_) { }
  ^
./displaycontroller.h:621:28: error: union member 'bitmapDrawingInfo' has a non-trivial default constructor
    BitmapDrawingInfo      bitmapDrawingInfo;
                           ^
./displaycontroller.h:491:8: note: because type 'fabgl::BitmapDrawingInfo' has no default constructor
struct BitmapDrawingInfo {
       ^
./displaycontroller.h:496:3: note: implicit default constructor suppressed by user-declared constructor
  BitmapDrawingInfo(int X_, int Y_, Bitmap const * bitmap_) : X(X_), Y(Y_), bitmap(bitmap_) { }
  ^
./displaycontroller.h:623:28: error: union member 'pixelDesc' has a non-trivial default constructor
    PixelDesc              pixelDesc;
                           ^
./displaycontroller.h:604:10: note: because field of type 'Point' has a user-provided default constructor
  Point  pos;
         ^
./fabutils.h:212:3: note: declared here
  Point() : X(0), Y(0) { }
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
11 warnings and 20 errors generated.
make[1]: *** [canvas.o] Error 1
make: *** [all] Error 2

%

**Comment by snakebyte69** [comment]
cargo run -r

Needs
vdp_console8.so

**Comment by spacehaven** [comment]
I was able to get it working by adding these to the userspace-vdp Makefile: -std=gnu++11 -Wno-c++11-narrowing

`CFLAGS = -Wall -O2 -std=gnu++11 -Wno-c++11-narrowing  -fmax-errors=1 -g -I. -I./dispdrivers`

I also had to manually create a /opt/local/lib directory, although it didn't look like it put anything there. I might've misread an error though.

**Comment by peterhellberg** [comment]
I was also able to get it working under macOS Sonoma by: 

1. Adding `-Wno-c++11-narrowing` to CFLAGS in `src/vdp/Makefile` and in `src/vdp/userspace-vdp-gl/src/Makefile`
2. Including `#include <cstddef>` in `src/vdp/userspace-vdp-gl/src/userspace-platform/Stream.h` (in order to have `std::size_t` declared)

**Comment by omiq** [comment]
Oh, for future people who have issues, you also need SDL2 and the environment variable to point to the library:

```export LIBRARY_PATH="$LIBRARY_PATH:/opt/homebrew/Cellar/sdl2/2.28.4/lib"```

**Comment by MikeDX** [comment]
The SDL2 issue can also be resolved by changing build.rs to include the following (where sdl2-confing --libs shows /opt/homebrew/lib)

```
    println!("cargo:rustc-link-search=native=/opt/homebrew/lib");  // Update this path to the correct location
    println!("cargo:rustc-link-lib=SDL2");
```

```
use std::process::Command;

fn main() {
    println!("cargo:rustc-link-search=native=/opt/homebrew/lib");  // Update this path to the correct location
    println!("cargo:rustc-link-lib=SDL2");
    Command::new("make").status().expect("failed to build VDP");
}
```

**Comment by prgp** [comment]
I found that after
```
brew install sdl2
```
using
```
export LIBRARY_PATH="$LIBRARY_PATH:/opt/homebrew/lib"
```
worked for me.

I required both the following to get the emulator to build successfully and be runnable:
* the `-Wno-c++11-narrowing` addition to `src/vdp/Makefile`
* the `#include <cstddef>` addition in `src/vdp/userspace-vdp-gl/src/userspace-platform/Stream.h`

I wish I had read this issue before I attempted to build, would have saved me a little bit of time :-D

---

Built on (as per System Report):
```
Model Identifier:         Macmini9,1
Chip:                     Apple M1
Total Number of Cores:    8 (4 performance and 4 efficiency)
Memory:                   16 GB
System Version:           macOS 13.6 (22G120)
```
Using `clang` as my C++ compiler, I have not tried gcc ...

**Comment by fayep** [comment]
pushed changes to #17

**Comment by snakebyte69** [comment]
> I was also able to get it working under macOS Sonoma by:
> 
> 1. Adding `-Wno-c++11-narrowing` to CFLAGS in `src/vdp/Makefile` and in `src/vdp/userspace-vdp-gl/src/Makefile`
> 2. Including `#include <cstddef>` in `src/vdp/userspace-vdp-gl/src/userspace-platform/Stream.h` (in order to have `std::size_t` declared)
> 
> <img alt="Screenshot 2023-10-19 at 15 37 25" width="982" src="https://user-images.githubusercontent.com/565124/276633064-79546b82-e9cc-454d-9886-780fe91f33fe.png">

Can we get all these changes added to the MakeFile so newbies can build this for macOS?

**Comment by snakebyte69** [comment]
CFLAGS = $(EXTRA_FLAGS) -Wall -O2 -fmax-errors=1 -std=c++11 -g -I. -I./dispdrivers -I./userspace-vdp-gl/src -I./userspace-vdp-gl/src/userspace-platform -I./userspace-vdp-gl/src/dispdrivers

Where does this go?
-Wno-c++11-narrowing

**Comment by snakebyte69** [comment]
Again here where does it go?
CFLAGS = $(EXTRA_FLAGS) -Wall -O2 -fPIC -DUSERSPACE -g -std=c++11 -I. -I./dispdrivers -I./userspace-platform

**Comment by snakebyte69** [comment]
This now builds using the updated files which I posted in the Agon Programmers Discord

**Comment by snakebyte69** [comment]
I get the following run time error.

% ~/GitHub/tomm/fab-agon-emulator/fab-agon-emulator ; exit;
thread 'main' panicked at 'called Result::unwrap() on an Err value: DlOpen { desc: "dlopen(./firmware/vdp_quark104.so, 0x0005): tried: './firmware/vdp_quark104.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS./firmware/vdp_quark104.so' (no such file), '/usr/lib/./firmware/vdp_quark104.so' (no such file, not in dyld cache), './firmware/vdp_quark104.so' (no such file)" }', src/vdp_interface.rs:43:77
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

**Comment by snakebyte69** [comment]
The firmware is there the ./firmware might need to be a /firmware or a ../firmware

**Comment by snakebyte69** [comment]
This happens when I open it from the Directory Windows
---
It works if I run it from the command line like this
./fab-agon-emulator

**Comment by snakebyte69** [comment]
it would be nice to have this running from the
- usr/local/bin
directory

**Comment by snakebyte69** [comment]
It would also be nice if it could run as an app sitting on the Desktop that you could double click

**Comment by snakebyte69** [comment]
Here's a summary
- Use Github to clone the source code
- from the directory GitHub/tomm/fab-agon-emulator

% BREW INSTALL SDL2
% PLATFORM=mac make

**Comment by snakebyte69** [comment]
Update

% BREW INSTALL SDL2
% make

to run the emulator
% ./fab-agon-emulator

**Comment by snakebyte69** [comment]
This issue can be closed the warnings can be fixed by detecting the OS and setting appropriate CFLAGS
