### ISSUE TITLE
build failed on Windows machine

### ISSUE THREAD

**Issue by luisvolkyazul** [tomm/fab-agon-emulator#8]
Compiling fab-agon-emulator v0.7.5 (C:\Users\busyr\Downloads\fab-agon-emulator-main\fab-agon-emulator-main)
error: failed to run custom build command for `fab-agon-emulator v0.7.5 (C:\Users\busyr\Downloads\fab-agon-emulator-main\fab-agon-emulator-main)`

Caused by:
  process didn't exit successfully: `C:\Users\busyr\Downloads\fab-agon-emulator-main\fab-agon-emulator-main\target\release\build\fab-agon-emulator-292c5b592f41ba87\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at build.rs:4:35:
  failed to build VDP: Error { kind: NotFound, message: "program not found" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by astralaster** [comment]
You are missing make. https://gnuwin32.sourceforge.net/packages/make.htm

**Comment by astralaster** [comment]
# How to build on windows with mingw

* Install rustup from https://rustup.rs/
* rustup toolchain install stable-x86_64-pc-windows-gnu
* rustup default stable-x86_64-pc-windows-gnu
* Install make winget install GnuWin32.Make
* add C:\Program Files (x86)\GnuWin32\bin to path
* Install mingw64 from https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0mcf-16.0.6-11.0.1-ucrt-r2/winlibs-x86_64-mcf-seh-gcc-13.2.0-llvm-16.0.6-mingw-w64ucrt-11.0.1-r2.zip
* extract to C:\mingw64 and add C:\mingw64\bin to path
* get SDL2 from https://github.com/libsdl-org/SDL/releases/download/release-2.28.3/SDL2-devel-2.28.3-mingw.zip
* extract to C:\Users\<user>\.rustup\toolchains\stable-x86_64-pc-windows-gnu
* copy SDL2.dll to the root of the project
* run `cargo build --release` in the root of the project
* manually copy built vdp*.so files from userspace-vdp to the root of the project
* run `cargo run --release` in the root of the project

**Comment by astralaster** [comment]
Did you add make to your path?

**Comment by astralaster** [comment]
The error basically says it failed to run "make". So there must be something wrong with your make installation.

**Comment by astralaster** [comment]
It fails to link SDL2. So it's missing a .lib file for SDL2. Did you extract the downloaded SDL2 to the rust up Toolchain directory?
